name: Update data in database
# This workflow is triggered on pushes to master (when a PR is merged) that include changes in the app/data directory.
on:
  push:
    branches:
      - master
    paths: 
      - 'app/data/*'
jobs:
  build:
    name: Generate data and update db
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Set environment and update data in DB
      run: |
        pipenv install --dev
        cd app/data
        sed -i 1d time_series_export.csv
        psql postgres://${{ secrets.DB_NAME }}:${{ secrets.DB_PASS }}@${{ secrets.DB_HOST }}/${{ secrets.DB_USER }} "sslmode=disable" << EOF
        TRUNCATE TABLE covid_timeseries;
        SET datestyle = mdy;
        \copy "covid_timeseries" FROM 'time_series_export.csv' CSV;
        EOF
